# Generated by Django 4.1.2 on 2023-01-15 09:40

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20221217_1748"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=20, validators=[blog.validators.title_val]
            ),
        ),
    ]
